/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import dominio.ColorFicha;
import dominio.Jugador;
import dominio.Partida;


/**
 *
 * @author Hiram García
 */
public class FrmSeleccion extends FrmBase implements Observer{

    /**
     * Creates new form FrmSeleccion
     */
     private Partida partidaSelec;
    private Jugador jugadorSelec;
    public FrmSeleccion(Partida partida, Jugador jugador) {
        partidaSelec=partida;
        jugadorSelec=jugador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtJugador = new javax.swing.JTextField();
        btnAzul = new javax.swing.JButton();
        btnRojo = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnAmarillo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJugador.setBorder(null);
        jPanel1.add(txtJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 240, 30));

        btnAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/jAzul.png"))); // NOI18N
        btnAzul.setToolTipText("");
        btnAzul.setBorder(null);
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });
        jPanel1.add(btnAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 92, 92));

        btnRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/jRojo.png"))); // NOI18N
        btnRojo.setBorder(null);
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 92, 92));

        btnVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/jVerde.png"))); // NOI18N
        btnVerde.setBorder(null);
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 92, 92));

        btnAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/jAmarillo.png"))); // NOI18N
        btnAmarillo.setBorder(null);
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });
        jPanel1.add(btnAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 92, 92));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/btnCancelar.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, -1, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/btnAceptar.png"))); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dibujos/menuSeleccion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        // TODO add your handling code here:
        quitarColor(ColorFicha.AZUL);
        if(jugadorSelec.getColor()!=null){
            mostrarColor(jugadorSelec.getColor());
        }
       Jugador jug = partidaSelec.getJugadores().get(partidaSelec.getJugadores().indexOf(jugadorSelec));
       jugadorSelec = jug;
       jugadorSelec.setNombre(txtJugador.getText());
       jugadorSelec.setColor(ColorFicha.AZUL);
       partidaSelec.getJugadores().set(partidaSelec.getJugadores().indexOf(jug), jugadorSelec);
       partidaSelec.setJugadorTurno(jugadorSelec);
        
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       if (jugadorSelec.getColor() != null && !txtJugador.getText().isEmpty()) {
        FrmTablero frmTablero=new FrmTablero(partidaSelec,jugadorSelec);
        frmTablero.setVisible(true);
        dispose();
       }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        getFrmInicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        // TODO add your handling code here:
        quitarColor(ColorFicha.ROJO);
        if(jugadorSelec.getColor()!=null){
            mostrarColor(jugadorSelec.getColor());
        }
       Jugador jug = partidaSelec.getJugadores().get(partidaSelec.getJugadores().indexOf(jugadorSelec));
       jugadorSelec = jug;
       jugadorSelec.setNombre(txtJugador.getText());
       jugadorSelec.setColor(ColorFicha.ROJO);
       partidaSelec.getJugadores().set(partidaSelec.getJugadores().indexOf(jug), jugadorSelec);
       partidaSelec.setJugadorTurno(jugadorSelec);
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        // TODO add your handling code here:
        quitarColor(ColorFicha.VERDE);
        if(jugadorSelec.getColor()!=null){
            mostrarColor(jugadorSelec.getColor());
        }
        Jugador jug = partidaSelec.getJugadores().get(partidaSelec.getJugadores().indexOf(jugadorSelec));
       jugadorSelec = jug;
       jugadorSelec.setNombre(txtJugador.getText());
       jugadorSelec.setColor(ColorFicha.VERDE);
       partidaSelec.getJugadores().set(partidaSelec.getJugadores().indexOf(jug), jugadorSelec);
       partidaSelec.setJugadorTurno(jugadorSelec);
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        // TODO add your handling code here:
        quitarColor(ColorFicha.AMARILLO);
        if(jugadorSelec.getColor()!=null){
            mostrarColor(jugadorSelec.getColor());
        }
         Jugador jug = partidaSelec.getJugadores().get(partidaSelec.getJugadores().indexOf(jugadorSelec));
       jugadorSelec = jug;
       jugadorSelec.setNombre(txtJugador.getText());
       jugadorSelec.setColor(ColorFicha.AMARILLO);
       partidaSelec.getJugadores().set(partidaSelec.getJugadores().indexOf(jug), jugadorSelec);
       partidaSelec.setJugadorTurno(jugadorSelec);
    }//GEN-LAST:event_btnAmarilloActionPerformed

    /**
     * @param args the command line arguments
     */
  public void quitarColor(ColorFicha color) {
        switch (color) {
            case ROJO:
                btnRojo.setVisible(false);
                break;
            case AMARILLO:
                btnAmarillo.setVisible(false);
                break;
            case VERDE:
                btnVerde.setVisible(false);
                break;
            case AZUL:
                btnAzul.setVisible(false);
                break;
            
        }
    }

    public void mostrarColor(ColorFicha color) {
        switch (color) {
            case ROJO:
                btnRojo.setVisible(true);
                break;
            case AMARILLO:
                btnAmarillo.setVisible(true);
                break;
            case VERDE:
                btnVerde.setVisible(true);
                break;
            case AZUL:
                btnAzul.setVisible(true);
                break;
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtJugador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
